//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDuck.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XmlTestDocs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XmlTestDocs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NDuck.TestData.XmlTestDocs", typeof(XmlTestDocs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;log4net&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:log4net.Appender.AdoNetAppender&quot;&gt;
        ///            &lt;summary&gt;
        ///            Appender that logs to a database.
        ///            &lt;/summary&gt;
        ///            &lt;remarks&gt;
        ///            &lt;para&gt;
        ///            &lt;see cref=&quot;T:log4net.Appender.AdoNetAppender&quot;/&gt; appends logging events to a table within a
        ///            database. The appender can be configured to specify the connection 
        ///            string by s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string log4net {
            get {
                return ResourceManager.GetString("log4net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;NHibernate&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:NHibernate.Action.BulkOperationCleanupAction&quot;&gt;
        ///            &lt;summary&gt;
        ///            Implementation of BulkOperationCleanupAction.
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;T:NHibernate.Action.IExecutable&quot;&gt;
        ///            &lt;summary&gt;
        ///            An operation which may be scheduled for later execution.
        ///            Usually, the operation is a database inser [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NHibernate {
            get {
                return ResourceManager.GetString("NHibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;OutputPath&quot;: &quot;./nduck&quot;,
        ///    &quot;Assemblies&quot;: [ &quot;Assembly1&quot;, &quot;Assembly2&quot; ],
        ///    &quot;Verbosity&quot;: &quot;Debug&quot;,
        ///    &quot;ContentDirectory&quot;: &quot;./content&quot;
        ///}
        ///.
        /// </summary>
        internal static string TestOptions {
            get {
                return ResourceManager.GetString("TestOptions", resourceCulture);
            }
        }
    }
}
